
apiVersion: v1
kind: Service
metadata:
  name: api-health-monitor-service
spec:
  type: NodePort
  selector:
    app: api-health-monitor
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
