
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-health-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-health-monitor
  template:
    metadata:
      labels:
        app: api-health-monitor
    spec:
      containers:
      - name: api-health-monitor
        image: spacejet/api-health-monitor-ui:latest
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet: { path: /health, port: 8090 }
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: /health, port: 8090 }
          initialDelaySeconds: 10
          periodSeconds: 5
